@startuml
actor Cliente
boundary ApuestaResource
participant PartidoSchema
participant ApuestaSchema
participant PartidoModel
participant ApuestaModel
database data

Cliente --> ApuestaResource: get all
ApuestaResource --> PartidoModel: get all(finalizado = false)
PartidoModel --> data: select all
PartidoModel <-- data: registrs partidos finalizados
PartidoModel --> PartidoSchema: dump many = true
PartidoSchema --> ApuestaResource: colección en Json
ApuestaResource --> Cliente

Cliente --> ApuestaResource: post
ApuestaResource --> ApuestaModel: Guardar apuesta
ApuestaModel --> data: Insert
data <-- ApuestaModel: Object
ApuestaModel --> ApuestaSchema: Dump Object
ApuestaSchema --> ApuestaResource: Json
ApuestaResource --> Cliente


@enduml